[build-system]
requires = [
    "setuptools",
    "setuptools_scm",
  ]
build-backend = "setuptools.build_meta"

# allow openalea to be a namespace package
[tool.setuptools.packages.find]
where = ["src"]

# enable dynamic version based on git tags
[tool.setuptools_scm]
# Format version to ease alignment with conda/meta.yaml tag-based versioning
fallback_version = "2.0.0.dev0"
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"

[project]
name = "openalea.hydroroot"
authors = [
  { name = "Christophe Pradal" },
  { name = "Yann Boursiac" },
  { name = "Fabrice Bauget" },
  { name = "Mikael Lucas" },
  { name = "Christophe Godin" },
  { name = "Christophe Maurel" },
]
description = "OpenAlea.HydroRoot is a hydraulic root architecture modelling and a root architecture system generator package."
readme = "README.rst"
license = "CECILL-C"
license-files = ["LICEN[CS]E*"]
requires-python = ">=3.0"
classifiers = [
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering",
]
dynamic = ["version"]
#version = "2.0.1"
dependencies = [
    "pandas",
    "numpy",
    "scipy",
    "pyyaml",
]


# section specific to conda-only distributed package (not used by pip yet)
[tool.conda.environment]
channels = [
  "openalea3",
  "conda-forge"
]
dependencies = [
    "openalea.mtg",
    "openalea.plantgl",
    "openalea.oawidgets",
    "yaml",
    "rsml",
    "matplotlib-base" # does not exist in pip
]

[project.optional-dependencies]
test = ["pytest"]
notebook = ["jupyter"]
doc = [
  "sphinx-favicon",
  "sphinx-rtd-theme",
  "pydata-sphinx-theme",
  "myst-parser",
  "nbsphinx",
  "sphinx-copybutton",
]

[project.urls]
Homepage = "https://hydroroot.rtfd.io/"
"Bug Tracker" = "https://github.com/openalea/hydroroot/issues"
Discussions = "https://github.com/openalea/hydroroot/discussions"
Changelog = "https://github.com/openalea/hydroroot/releases"

#[tool.setuptools.dynamic]
#readme = {file = ["README.rst"]}

[tool.setuptools.package-data]
"hydroroot_data" = ["*"]

[project.entry-points."wralea"]
"hydroroot" = "openalea.hydroroot_wralea"


