#%YAML

#All parameters should be in SI units

#Few parameters may be set to list of float or integer allowing to run successive simulation
# there are two syntaxes:
#       [x1, ..., xn] or range(start, end, step)
#       eg. range(0.02, 0.09, 0.02) or [0.02, 0.04, 0.06, 0.08] will give the same results
#       the parameter will take successively the values 0.02, 0.04, 0.06 and 0.08

archi:
    #if read_architecture is true then architecture will be constructed from the file(s) given by input_dir and input_file
    #otherwise the architecture will be generated according to the parameters
    read_architecture: False

    #Input architecture from scanned image (distance_from_base_(mm) \t lateral_root_length_(mm) \t order)
    #folder name
    input_dir: data/

    #File name:
    #may be a list of names, eg. [file1, file2, file3] wildcar may be used
    input_file: [200619-YBFB-Col-2-cut-n-flow-archi2.txt]

    seed:

    #file names with length laws relative path
    #file format: "LR_length_mm" ; "relative_distance_to_tip"
    #laws used to generate lateral roots of the 1st order (1_order_law), and lateral roots of order above 1 (2_order_law)
    length_file:
        - data/length*order1*.csv
        - data/length*order2*.csv

    #length of the primary root
    #float or list of float
    #unit: m
    primary_length: 0.16

    #branching delay
    #float or list of float
    #unit: m
    branching_delay: 2.0e-3

    #branching variability
    #float between [0 ; 1], 0.25 means 25%
    branching_variability: 0.25

    #maximum roots order
    order_max: 4

    #vertices length
    #unit: m
    segment_length: 1.0e-3

    #part of roots without any lateral root, distance from tip
    #float or list of float
    #unit: m
    nude_length: 0.2

    #reference radius of the primary root
    #float
    #unit: m
    ref_radius: 7.0e-5

    #radius decrease factor applied when increasing order
    #float
    #radius lateral order n: r = order_decrease_factor^n * ref_radius
    order_decrease_factor: 0.7

hydro:
    #radial conductivity
    #float
    #unit: microL/(s.MPa.m**2)
    k0: 737.5

    #axial_conductance_data
    #   - [x1, ......, xn]
    #   - [K1, ....., Kn]
    #list of float
    #unit: microL.m/(s.Mpa)
    axial_conductance_data:
        - [0, 1.5e-2, 4.0e-2, 6.0e-2, 7.65e-2, 9.65e-2, 11.75e-2, 14.85e-2, 19.75e-2]
        - [ 3.98832280e-05, 1.54649138e-05, 1.56646991e-04, 4.33503238e-04,
            5.56512304e-04, 9.26583733e-04, 1.40617896e-03, 1.38745517e-03,
            3.96278962e-04 ]

experimental:
    #water flux at the root base
    #float
    #unit: microL/s
    Jv:  0.00723

    #hydric potential outside the roots (pressure chamber)
    #float
    #unit: MPa
    psi_e: 0.401325

    #hydric potential at the root base (e.g. atmospheric pressure for decapitated plant)
    #float
    #unit: MPa
    psi_base: .101325

output:
    #distance from the base for intercepts calculation
    # float or list of float
    #unit: m
    intercepts: []

    #factor to explore a k0 range
    # float or list of float
    radfold: 1.

    #like radfold but apply to axial_conductance_data
    axfold: 1.

    #number of run with the same set of parameters i.e. number of different seeds
    #integer
    #enable only if read_architecture is false
    run_nb: 1
